[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "clean-folder"
version = "1.0"
description = "Clean folder script"
authors = [{name = "Siracenco Serghei", email = "siracencoserghei@gmail.com"}]